// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FBISDNETCore.MVC.Models;

/// <summary>
/// Cross-reference table mapping products to related product documents.
/// </summary>
public partial class ProductDocument
{
    /// <summary>
    /// Product identification number. Foreign key to Product.ProductID.
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Document identification number. Foreign key to Document.DocumentNode.
    /// </summary>
    public HierarchyId DocumentNode { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    public DateTime ModifiedDate { get; set; }

    public virtual Document DocumentNodeNavigation { get; set; }

    public virtual Product Product { get; set; }
}